### ISSUE TITLE
Steps and timeline for a Beta upload AMSD

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#2]
Could we do a test upload of data to the AMSD?
I can provide an up-to-date .tsv file together with images on a USB drive whenever it suits. 
I don't mind if the interface is very basic, just to begin with.

**Comment by xrotwang** [comment]
@perezkelly we have a (public) data repository for this project, too: https://github.com/clld/amsd-data (you should have received an invitation to it). At least the non-media-file data could be added (and curated) there.

**Comment by Bibiko** [comment]
@perezkelly as for the image files I'm just preparing a command for us to upload all images to our media server. Once it runs you can upload a zip archive of all image to owncloud/dropbox/... and pass us the url, then we'll upload these images.

**Comment by Bibiko** [comment]
@perezkelly to upload a new TSV file simply go to https://github.com/clld/amsd-data/tree/master/org_data , press `Upload files`, select your new data file and upload it (you will ask for a short commit message)

**Comment by perezkelly** [comment]
Terrific! I'll upload the tsv shortly

**Comment by perezkelly** [comment]
Done. 
Should I click "Commit directly to the master branch."? Or "Create a new branch for this commit and start a pull request."?

**Comment by xrotwang** [comment]
committing to master is ok, I think. Maybe at a later stage, maybe with more collaborators we would want to switch to adding data only after review, and then "new branch" would be the better option.

**Comment by perezkelly** [comment]
Ok, done now. This is just a 'test it and see' data upload anwyay.

**Comment by Bibiko** [comment]
@perezkelly a side note to your last commit of 
https://github.com/clld/amsd-data/blob/master/org_data/20181026-Message_sticks_bkp-records.tsv - Is this the final structure of your data? The number of columns and the header names differ from your last data file `20180215-Message_sticks_bkp-records.tsv`. Please think about this structure whether it fulfils your needs etc.

**Comment by perezkelly** [comment]
Yes, the number of columns is different. I've been separating the data differently, generating new fields and eliminating others.
