### ISSUE TITLE
Interface structure under 'Pre-filtering of multiple shared values'

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#28]
Loving the nice clean and functional interface! I would like to make it even simpler if possible.

_Under 'Pre-filtering of multiple shared values'_:  
-Please put 'Any field' at the top in the left. This will be the most useful search since it is the most general. It's the one the gets used the most in the OCCAMS data entry interface.
-Add 'Message' just to the right of 'Any field', then 'Semantic domains' and 'Keywords'

<img width="929" alt="Screen Shot 2019-08-01 at 15 37 50" src="https://user-images.githubusercontent.com/9706926/62298291-09ca4380-b473-11e9-9972-2bba90ce1a13.png">

**Comment by xrotwang** [comment]
The pre-filtering doesn't seem to work for more than one filter criterion. As soon as I add the second criterion, **all** sticks are selected.

**Comment by perezkelly** [comment]
Could this still be done??
<img width="832" alt="Screen Shot 2020-11-30 at 11 51 08 am" src="https://user-images.githubusercontent.com/9706926/100558424-876dc000-3302-11eb-8070-ff634f8db0c2.png">

**Comment by Bibiko** [comment]
@perezkelly applied the desired changes - to handle such data table search persistently, one has to type the search string into a field and submit the search by pressing ENTER or the magnifier button

**Comment by perezkelly** [comment]
Looks great, thank you. This makes my search experience much better.
