### ISSUE TITLE
Interface structure in main list (under 'Showing 1 to 100 of 1,055 entries')

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#29]
In the list of entries, directly under 'Showing 1 to 100 of 1,055 entries':
-please remove the columns headed 'Description', 'Message', 'Keywords', 'Any field'. Then please expand the 'Image' column so that it takes up _all_ the space formerly occupied by the deleted columns.  In the search results it will be really important to see as much of the image thumbnails as possible. 
<img width="984" alt="Screen Shot 2019-08-01 at 15 44 26" src="https://user-images.githubusercontent.com/9706926/62298569-8a893f80-b473-11e9-9911-a69a382796e3.png">

**Comment by Bibiko** [comment]
I left the 'Any Field' search since I found a way to move it to the pre-filter bar.
