### ISSUE TITLE
Pop up sensitivity notice

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#3]
I am trying to reconcile all the different access conditions of collecting institutions who have contributed to the database. Some are strict and fiddly, most are pretty relaxed. I have drafted a general statement that covers just about everything and I would like to include it as a pop-up notice the first time a user visits the AMSD. It is inspired by the sensitivity notice on Austlang which will pop up when you first access it, but then it disappears until you start a new session: https://collection.aiatsis.gov.au/austlang/search

The draft wording is: 
### Sensitivity notice
The images and metadata within this database are the property of the collecting institutions and are made available at the discretion of their Indigenous advisory boards. 

**Artefacts**
Message sticks are public communication devices that go by many different names in Australian languages. Note that the English term 'message stick' is sometimes mistakenly used to refer to _non_-public sacred objects, of similar appearance, used in parts of Central and Western Australia.  _No sacred materials are included here._

**Access conditions**
Re-use of images is subject to the conditions stipulated by the collecting institutions and their Indigenous advisory boards; please pay attention to the copyright information in each entry as well as the links to the original sources. 

**Deceased persons**
Users of the database should be aware that in some Aboriginal and Torres Strait Islander communities, seeing images of deceased kin may cause distress and violate cultural prohibitions. A small number of entries includes images of people who are now deceased.

**Comment by xrotwang** [comment]
Hm. We really don't keep track of users and sessions - for various reasons, among them privacy concerns and allowing easy automated access, e.g. to crawlers. So this isn't really an option.

**Comment by perezkelly** [comment]
OK, the use of sessions is not really the important part – lets forget it. Can this notice appear with a button at the bottom that says "Enter the database"?

**Comment by xrotwang** [comment]
Yes, that shouldn't be difficult. But all individual pages - i.e. "the database" will still be bookmarkable and openly accessible. So there's no guarantee people can only get to the data after having read the notice.

**Comment by perezkelly** [comment]
Totally fine with me, as long as its on the front page. Mostly I want to demonstrate to the participating museums that I'm treating the data respectfully.

**Comment by perezkelly** [comment]
Updated wording:

### Sensitivity notice

**Artefacts**
Message sticks are public communication devices that go by many different names in Australian languages. Note that the English term 'message stick' is sometimes mistakenly used to refer to non-public sacred objects, of similar appearance, used in parts of Central and Western Australia. _No sacred materials are included here._
**Access conditions**
A large part of this dataset is comprised of images and metadata willingly contributed by collecting institutions, with the oversight of their Indigenous advisory boards. Access to this material remains at the discretion of these institutions and boards. Re-use of images in any way is subject to the conditions stipulated by the institutions themselves and may vary within the dataset. Please pay attention to the copyright information in each entry as well as the links to the original sources.
**Deceased persons**
Users of the dataset should be aware that in some Aboriginal and Torres Strait Islander communities, seeing images of deceased kin may cause distress and violate cultural prohibitions. A small number of entries includes images of people who are now deceased.
**Digital repatriation policy**
The images and metadata within this dataset are sourced from many locations across the world, but have a special value within their communities of origin. We respect the rights of Indigenous communities to retain full access to their cultural heritage and will make every effort to help re-archive materials of interest in local repositories.

**Comment by perezkelly** [comment]
Please replace the following text on the front page:
"The Australian Message Stick Database contains data licensed under various conditions depending on agreements with museums (see individual records for details). No restricted or sacred items are included. It has been developed by The Mint Research Group at The Max Planck Institute for the Science of Human History."
With the following sensitivity notice:

####Sensitivity notice
**Artefacts and entries**
Message sticks are public communication devices that go by many different names in Australian languages. Note that the English term 'message stick' is sometimes mistakenly used to refer to non-public sacred objects, of similar appearance, used in parts of Central and Western Australia. No sacred materials are included here. Each entry in the dataset is created from a composite of public sources, including manuscripts, published papers, and museum catalogues. The AMSD makes no representations, warranties or assurances (either expressed or implied) as to the accuracy, currency or completeness of the cited sources that inform each entry. Users of this dataset are also advised that locations of language groups or places shown on the map are approximate and are not to be used for land or native title claims. 

**Access conditions, copyright and ICIP**
The AMSD does not claim or own any copyright or ICIP over any of the information, including records produced through our own field research. The dataset is intended for personal study only. For any other uses please review information in each record to find the traditional owners of the material (if available),  the institution responsible for copyright management, and the original sources. Note that all non-public sources are excluded from the dataset. If you believe that we have included a source in error, please contact us.

**Deceased persons**
Users of the dataset should be aware that in some Aboriginal and Torres Strait Islander communities, seeing images of deceased kin may cause distress and violate cultural prohibitions. A small number of entries includes images of people who are now deceased.

**Digital repatriation policy**
The images and metadata within this dataset are sourced from many locations across the world, but have a special value within their communities of origin. We respect the rights of Indigenous communities to retain full access to their cultural heritage and control over ICIP. We will make every effort to help re-archive materials of interest in local repositories with the participation of collecting institutions.
