### ISSUE TITLE
Map: add thumbnail to call-out box

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#33]
Since the visual aspect of message sticks is most important it would be great if a thumbnail image could be added to the call out box when you click on a dot on the map. This would allow users to quickly identify a stick by sight, or make quick comparisons between regions. 

The best image is always the one with the filename that is earliest in alphabet or numeric order.

Example of what I have in mind:
<img width="708" alt="Screen Shot 2019-08-28 at 15 02 56" src="https://user-images.githubusercontent.com/9706926/63858226-6e5ebc80-c9a5-11e9-9b58-6f2f35658663.png">

**Comment by Bibiko** [comment]
@perezkelly - please try amsd.clld.org

**Comment by perezkelly** [comment]
Perfect, thanks!
