### ISSUE TITLE
DOIs for each entry

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#4]
Is it feasible to mint unique DOIs for each of the 1051 entries? Often I need to cite or crossreference a specific message stick and I realise there is no way of doing this. OCCAMS assigns a unique number beginning with 500_ but this doesn't end up in the .tsv for some reason. DOIs would be a fantastic solution.

**Comment by xrotwang** [comment]
In any case each entry will get its own URL - which we intend to keep stable. But we could also use the DOI minting service provided by MPDL to then register each of these, and get a DOI in return. Of course this will put the burden on our shoulders of updating the DOI registry, should we ever move any of this content ...

**Comment by perezkelly** [comment]
As long as there is a short and absolutely permanent identifier I will be happy. That way I will be able to reference individual artefacts in papers, glossaries and my own draft notes. Eg, "Signs representing female participants in initiation ceremonies are seen on artefact 500_29308 and 500_4747, both of which were collected in western Queensland. Four related artefacts (500_2973, 500_2903, 500_5431 and 500_9097) are pigmented with ochre". This could be approximated with a DOI but also with a short URL eg, something like https://amsd.clld.org/3285, could be referenced as "3285". If DOIs are the solution, I will happily volunteer to update the registry whenever necessary. It's only 1050 entries and a student assistant could help with this.

**Comment by xrotwang** [comment]
Registering the DOIs now is presumably not much of a problem, i.e. can be done automatically. The problem with updating is, that this will only be necessary when the URLs can no longer be maintained - e.g. because the department is closed and no one commits to keeping the servers running. So basically, when you close down things because you don't want to waste resources is the point where you'd have to invest resources in updating the DOI registry. That's the conundrum with DOIs - or any redirection layer which promises to be a longterm solution.

**Comment by perezkelly** [comment]
OK, that makes sense to me. I'm having a look now at other databases of visual material culture to think about alternative solutions.

**Comment by xrotwang** [comment]
We could do the following: Archive the invidual objects - I guess as a package consisting of image(s) and some metadata - with a service like ZENODO or MPDL's [edmond](https://edmond.mpdl.mpg.de/). That way, we would get a DOI, which will lead to the object and is under the control of an institution committed to longterm access. This DOI, of course, would not directly lead to the web site we are building, but for ZENODO there are ways to display this link somewhat prominently on the landing page. E.g. here https://doi.org/10.5281/zenodo.1312960 the "Cite the source dataset ..." could instead provide the URL at https://amsd.clld.org.

With this setup, the AMSD app would be just aggregating the metadata for the objects archived with ZENODO; i.e. basically serve as a catalog with ZENODO being the collection.

**Comment by perezkelly** [comment]
I love the ingenuity of this solution! In the meantime, however, I've asked around and it seems like nobody else is using DOIs for entries on similar kinds of visual-culture databases. Probably this is because all the drawbacks that you already mentioned. Instead, the preference is for project-internal IDs. I only wanted to avoid this because IDs have a way of proliferating - some museums, for example, have three or four IDs for the same object because of changing catalogue conventions. But I think it's the simplest way forward. So, for the time being I'm going to set aside the idea of using DOIs and think instead about generating project internal ids based on my existing filename conventions. I should be able to generate them relatively quickly.
