### ISSUE TITLE
New logo (typo on landing page)

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#41]
I noticed a typo in the logo: it should be Australian Message Stick Database, not Australian Message Sticks Database. 

<img width="1387" alt="Screen Shot 2020-11-30 at 11 54 38 am" src="https://user-images.githubusercontent.com/9706926/100558603-2bf00200-3303-11eb-89c2-9f0029bb56be.png">

Shelly has updated the logo. The correct one is here:
![Logo-Australian-Message-Stick-Lrg](https://user-images.githubusercontent.com/9706926/100558633-55109280-3303-11eb-9f80-eba60ac14a17.jpg)
I can provide a version with a smaller file size if necessary.

**Comment by Bibiko** [comment]
@perezkelly is now online - you might clear your browser's cache (or reload the home page several times) to see the new logo
