### ISSUE TITLE
Timeline for developing search interface

### ISSUE THREAD

**Issue by perezkelly** [clld/amsd#5]
I would like to submit an 'Announcing a new database' paper in January, since my status at the institute will change in February from 'staff' to 'research associate' and I may not have as much of an opportunity to work on it.
Is it possible to move forward on the creation of a search interface?
What sort of timeline is reasonable?

I've attached an (updated) wireframe for how this might look. 
[20181217-Database_wireframe.pdf](https://github.com/clld/amsd/files/2685196/20181217-Database_wireframe.pdf)

**Comment by xrotwang** [comment]
By default, clld apps are "resource oriented", i.e. they know different resources - i.e. instances of a particular data type. The resource here would be "message stick" and probably "image of message stick"? For these resources, clld apps auto-generate index pages, i.e. tables listing instances, and details pages for individual instances.

At least by default, these pages (which we basically get for free) would look somewhat different that what you propose. I'd still recommend @Bibiko starts with such a default app, and we take this as a starting point. What do you think @perezkelly ?

**Comment by perezkelly** [comment]
Sounds like a good place to start.

What I really want in the end is something that is consistent with the standard museum search interfaces. The software they use is called Collections Explorer (I think) and it sits on top of the data. There are various free open source versions that do pretty much the same thing, but it's fairly basic in any case. 

Here's an example of a Collections Explorer search of the National Museum of Australia with the raw search terms 'message', 'stick' and 'Western':
http://collectionsearch.nma.gov.au/ce/message%20stick%20Western?solrsort=score%20desc&&

**Comment by xrotwang** [comment]
I see. And yes, that looks like fairly straightforward faceted search. It may still be somewhat problematic to emulate this with clld's default table-based browsing. In the worst case, I think, we'd have to replace the front-end, i.e. replace tables and searchable columns by something custom. But we should be able to at least keep the clld backend.

**Comment by xrotwang** [comment]
And if this sounds like someone with a hammer, trying to see the nail in you proposal: Yes, that's exactly what I try to do :)

**Comment by perezkelly** [comment]
No worries – you're the experts when it comes to this sort of thing!

**Comment by perezkelly** [comment]
Hi Team,
Is there any chance of more progress on this?
At this stage the lack of a functioning database is holding up grant applications and thus keeping me unemployed! 

I'm still in Jena until September and I can meet any time. If there's any way of making it simpler or faster, I'm open to new ways of doing things.

Piers
